name: Build Result (No Push)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build result container (no push)
        run: |
          docker build -t sysdigassessment/${{ vars.RESULT_IMAGE_NAME }}:latest ./result

      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v6
        with:
            image-tag: sysdigassessment/${{ vars.RESULT_IMAGE_NAME }}:latest
            sysdig-secure-token: ${{ secrets.SYSDIG_API_TOKEN }}
            sysdig-secure-url: ${{ vars.SYSDIG_SECURE_URL }}

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
          category: sysdig-${{ vars.RESULT_IMAGE_NAME }}
